# Generated by Django 4.1.7 on 2023-04-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
    ]
